pub struct MessageType {}
pub struct ResultCode {}
pub struct ProtocolVersion {}
pub struct FramingCapabilities {}
pub struct BearerCapabilities {}
pub struct TieBreaker {}
pub struct FirmwareRevision {}
pub struct HostName {}
pub struct VendorName {}
pub struct AssignedTunnelId {}
pub struct ReceiveWindowSize {}
pub struct Challenge {}
pub struct ChallengeResponse {}
pub struct Q931CauseCode {}
pub struct AssignedSessionId {}
pub struct CallSerialNumber {}
pub struct MinimumBps {}
pub struct MaximumBps {}
pub struct BearerType {}
pub struct FramingType {}
pub struct CalledNumber {}
pub struct CallingNumber {}
pub struct SubAddress {}
pub struct TxConnectSpeed {}
pub struct RxConnectSpeed {}
pub struct PhysicalChannelId {}
pub struct PrivateGroupId {}
pub struct SequencingRequired {}
