name: Build, Lint and MiriTest
on: [push]
jobs:
  Build-Lint-Test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: |
          cargo fmt --all -- --check
      - name: Clippy
        run: |
          cargo clippy --features=fail-on-warnings
      - name: MiriTest
        run: |
          cargo miri test --features=fail-on-warnings
