name: Build, Lint and Test
on: [push]
jobs:
  Build-Lint-Test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build
      - name: Lint
        run: |
          cargo clippy
      - name: Test
        run: |
          cargo test
