name: Build, Lint and Test
on: [push]
jobs:
  Build-Lint-Test:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --features=fail-on-warnings
      - name: Lint
        run: |
          cargo clippy --features=fail-on-warnings
      - name: Test
        run: |
          cargo test --features=fail-on-warnings
